### PR TITLE
fix minor doc typo

### PR DESCRIPTION
**Pull request by jmorsecode**

### CODE REVIEW

**Comment by openstack-gerrit** [comment]
Thank you for contributing to openstack/ara!

openstack/ara uses Gerrit for code review.

If you have never contributed to OpenStack before make sure you have read the
getting started documentation:
http://docs.openstack.org/infra/manual/developers.html#getting-started

Otherwise please visit
http://docs.openstack.org/infra/manual/developers.html#development-workflow
and follow the instructions there to upload your change to Gerrit.

**Comment by dmsimard** [comment]
@jmorsecode hey, sorry about that. I'm happy to send the patch on your behalf or help you get started. Let me know if I can help.

**Comment by jmorsecode** [comment]
@dmsimard I'm not familiar with Gerrit, but if it only requires an ubuntu openid and git, I'll try to give it a shot!

**Comment by dmsimard** [comment]
@jmorsecode works for me, the tl;dr is:

    Sign up for launchpad: https://login.launchpad.net/+login
    Log in to gerrit: https://review.openstack.org/
    Set up your SSH key and gerrit username in the gerrit settings: https://review.openstack.org/#/settings/
    Install git-review (pip install git-review, yum install git-review, apt-get install git-review)
    Clone the repo
    Hack on things
    Commit
    "git review" to send the patch for review

ARA has it's own [docs on contribution](https://ara.readthedocs.io/en/stable/contributing.html) but that's the gist of it.

**Comment by jmorsecode** [comment]
Resubmitted using gerrit (hopefully). I appreciate the assistance. Hopefully next time it will be something more significant!

**Pull request closed without merging**
